export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: string;
  popularity: number; // For popularity sorting (0-100)
  isAi: boolean;
  freeLimitPerDay: number;
  icon: string;
  monthlyUses: string;
}

export const toolsList: Tool[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Format, validate, beautify, and minify your JSON data in real-time with instant syntax error highlighting.",
    category: "Developer Utilities",
    popularity: 98,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "120K",
  },
  {
    slug: "regex-tester",
    name: "Regex Tester & Visualizer",
    description: "Write and test regular expressions in real-time with highlight match visualization and capture groups.",
    category: "Developer Utilities",
    popularity: 92,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Braces",
    monthlyUses: "85K",
  },
  {
    slug: "unit-converter",
    name: "Unit & Currency Converter",
    description: "Convert physical dimensions (length, mass, temp) and fetch real-time exchange rates for global currencies.",
    category: "Converters",
    popularity: 88,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "60K",
  },
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    description: "Generate highly customizable, high-resolution QR codes for URLs, contact details, or text, and download them instantly.",
    category: "Media Tools",
    popularity: 94,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "QrCode",
    monthlyUses: "110K",
  },
  {
    slug: "resume-checker",
    name: "Resume / ATS Score Checker",
    description: "Analyze your resume against ATS requirements. Receive a detailed score (0-100) and structured tips for success.",
    category: "AI Engines",
    popularity: 99,
    isAi: true,
    freeLimitPerDay: 10,
    icon: "FileCheck",
    monthlyUses: "240K",
  },
  {
    slug: "resume-roaster",
    name: "AI Resume Roaster",
    description: "Upload your resume and get a witty, brutal, and hilarious roast from our AI detailing design and wording flaws.",
    category: "AI Engines",
    popularity: 97,
    isAi: true,
    freeLimitPerDay: 5,
    icon: "Flame",
    monthlyUses: "190K",
  },
  {
    slug: "base64-converter",
    name: "Base64 Encoder & Decoder",
    description: "Instantly encode text into Base64 format, or decode Base64 strings back to standard human-readable UTF-8.",
    category: "Converters",
    popularity: 90,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "75K",
  },
  {
    slug: "url-encoder",
    name: "URL Encoder & Decoder",
    description: "Convert strings into safe percent-encoded URL formats, or decode query parameters back to original values.",
    category: "Converters",
    popularity: 85,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "62K",
  },
  {
    slug: "html-encoder",
    name: "HTML Entity Encoder & Decoder",
    description: "Safely escape special characters like <, >, & into XML/HTML entities, or translate entity codes back to characters.",
    category: "Developer Utilities",
    popularity: 80,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Braces",
    monthlyUses: "44K",
  },
  {
    slug: "hash-generator",
    name: "Cryptographic Hash Generator",
    description: "Generate SHA-1, SHA-256, and SHA-512 hashes instantly from input text strings using browser Web Crypto APIs.",
    category: "Developer Utilities",
    popularity: 87,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "68K",
  },
  {
    slug: "uuid-generator",
    name: "UUID / GUID Batch Generator",
    description: "Generate batches of standard version 4 UUIDs instantly, with customization options for uppercase characters and hyphens.",
    category: "Developer Utilities",
    popularity: 91,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "94K",
  },
  {
    slug: "markdown-previewer",
    name: "Live Markdown Previewer",
    description: "Write Markdown code in the live editor and instantly preview the formatted layout output side-by-side.",
    category: "Media Tools",
    popularity: 89,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "QrCode",
    monthlyUses: "78K",
  },
  {
    slug: "jwt-decoder",
    name: "JWT Debugger & Parser",
    description: "Decode JSON Web Tokens instantly to check and parse Header, Payload, and Signature metadata fields.",
    category: "Developer Utilities",
    popularity: 93,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Braces",
    monthlyUses: "98K",
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter & Beautifier",
    description: "Clean up messy SQL queries. Formats keywords, indents logical conditions, and structures commands automatically.",
    category: "Developer Utilities",
    popularity: 86,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "58K",
  },
  {
    slug: "password-generator",
    name: "Password Generator & Strength Meter",
    description: "Generate cryptographically secure random passwords and view real-time strength/entropy estimations.",
    category: "Developer Utilities",
    popularity: 95,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "115K",
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Text Generator",
    description: "Create batches of random dummy paragraphs, sentences, or word strings from a standard Latin corpus.",
    category: "Media Tools",
    popularity: 83,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "QrCode",
    monthlyUses: "40K",
  },
  {
    slug: "hex-rgb-converter",
    name: "Hex to RGB / RGB to Hex",
    description: "Convert colors between Hexadecimal codes and RGB/RGBA channels, with a live background visual preview.",
    category: "Converters",
    popularity: 88,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "54K",
  },
  {
    slug: "css-gradient",
    name: "CSS Gradient Generator",
    description: "Design linear gradients with dual color picker stops and angles, and output clean copyable CSS style code.",
    category: "Media Tools",
    popularity: 92,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "QrCode",
    monthlyUses: "88K",
  },
  {
    slug: "diff-checker",
    name: "Text Diff Checker",
    description: "Compare two text blocks side-by-side and highlight additions and deletions line-by-line in real-time.",
    category: "Developer Utilities",
    popularity: 94,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Braces",
    monthlyUses: "105K",
  },
  {
    slug: "xml-formatter",
    name: "XML Formatter & Beautifier",
    description: "Format, structure, and indent raw XML strings with proper tag indents and clean spacing.",
    category: "Developer Utilities",
    popularity: 82,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "42K",
  },
  {
    slug: "json-yaml",
    name: "JSON to YAML Converter",
    description: "Convert JSON configuration objects into clean, indentation-structured YAML files instantly.",
    category: "Converters",
    popularity: 91,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "80K",
  },
  {
    slug: "yaml-json",
    name: "YAML to JSON Converter",
    description: "Convert nested YAML configuration blocks back to standard stringified JSON configurations.",
    category: "Converters",
    popularity: 89,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "72K",
  },
  {
    slug: "case-converter",
    name: "Text Case Converter",
    description: "Change text cases instantly to UPPERCASE, lowercase, Title Case, camelCase, snake_case, or kebab-case.",
    category: "Developer Utilities",
    popularity: 84,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Braces",
    monthlyUses: "49K",
  },
  {
    slug: "timestamp-converter",
    name: "Unix Epoch Timestamp Converter",
    description: "Translate Unix epoch timestamps (seconds/ms) to human-readable dates, and dates back to timestamps.",
    category: "Converters",
    popularity: 93,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "112K",
  },
  {
    slug: "word-counter",
    name: "Word & Character Counter",
    description: "Analyze paragraphs to count characters, words, sentences, and compute average reading speeds.",
    category: "Developer Utilities",
    popularity: 87,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Braces",
    monthlyUses: "63K",
  },
  {
    slug: "base32-converter",
    name: "Base32 Encoder & Decoder",
    description: "Convert alphanumeric texts to Base32 representation formats, and decode them back safely.",
    category: "Converters",
    popularity: 76,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "28K",
  },
  {
    slug: "url-parser",
    name: "URL Parser & Query Debugger",
    description: "Dissect a URL string into protocol, host, port, path, and extract a query parameters list.",
    category: "Developer Utilities",
    popularity: 89,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "79K",
  },
  {
    slug: "user-agent",
    name: "User Agent Parser",
    description: "Analyze user agent strings to extract OS, browser type, and layout rendering engines.",
    category: "Developer Utilities",
    popularity: 86,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "52K",
  },
  {
    slug: "base-converter",
    name: "Number Base Converter",
    description: "Convert numeric strings between Decimal, Binary, Octal, and Hexadecimal representations.",
    category: "Converters",
    popularity: 90,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "91K",
  },
  {
    slug: "morse-translator",
    name: "Morse Code Translator",
    description: "Translate Latin characters to Morse code sequences (dots/dashes) and translate Morse back to text.",
    category: "Converters",
    popularity: 81,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "38K",
  },
  {
    slug: "json-csv",
    name: "JSON to CSV / CSV to JSON",
    description: "Convert flat JSON arrays to CSV lists and CSV datasets back to formatted JSON arrays.",
    category: "Converters",
    popularity: 88,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "56K",
  },
  {
    slug: "string-utility",
    name: "String Utility & Text Stripper",
    description: "Prune whitespaces, replace substring matches, and strip duplicate newlines globally.",
    category: "Developer Utilities",
    popularity: 82,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Braces",
    monthlyUses: "41K",
  },
  {
    slug: "placeholder-image",
    name: "Placeholder Image Generator",
    description: "Formulate customizable placeholder SVG image files and inline source Data URLs.",
    category: "Media Tools",
    popularity: 90,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "QrCode",
    monthlyUses: "84K",
  },
  {
    slug: "regex-cheat-sheet",
    name: "RegEx Cheat Sheet & Generator",
    description: "Copy common regex tokens, anchors, and brackets with an interactive regex sandbox testing block.",
    category: "Developer Utilities",
    popularity: 92,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Braces",
    monthlyUses: "90K",
  },
  {
    slug: "html-preview",
    name: "HTML Sandbox & Live Previewer",
    description: "Write HTML markup, apply inline CSS styling rules, and preview layout rendering outputs in an iframe.",
    category: "Media Tools",
    popularity: 91,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "QrCode",
    monthlyUses: "83K",
  },
  {
    slug: "json-to-ts",
    name: "JSON to TypeScript Interface",
    description: "Generate copyable TypeScript interface typings from standard JSON structure schemas.",
    category: "Converters",
    popularity: 96,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "108K",
  },
  {
    slug: "cron-parser",
    name: "Crontab Expression Descriptor",
    description: "Translate space-separated crontab schedule expressions into human-readable English text summaries.",
    category: "Developer Utilities",
    popularity: 91,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "77K",
  },
  {
    slug: "curl-to-fetch",
    name: "cURL to Fetch Converter",
    description: "Convert raw cURL CLI requests into browser-compatible JavaScript fetch() scripts.",
    category: "Converters",
    popularity: 94,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "95K",
  },
  {
    slug: "slug-generator",
    name: "URL Slug Generator",
    description: "Transform alphanumeric sentences into clean, lowercase, URL-friendly slugs.",
    category: "Developer Utilities",
    popularity: 85,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Braces",
    monthlyUses: "58K",
  },
  {
    slug: "html-to-markdown",
    name: "HTML to Markdown Converter",
    description: "Translate markup tags and nested HTML blocks back into standard Markdown files.",
    category: "Converters",
    popularity: 88,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "69K",
  },
  {
    slug: "jwt-generator",
    name: "JWT Generator & Signer",
    description: "Tweak Header, Payload, and secret parameters to compile mock encoded JWT tokens.",
    category: "Developer Utilities",
    popularity: 92,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "84K",
  },
  {
    slug: "box-shadow",
    name: "CSS Box Shadow Generator",
    description: "Visually build CSS box-shadow properties with offset, blur, spread, and color sliders.",
    category: "Media Tools",
    popularity: 95,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "QrCode",
    monthlyUses: "102K",
  },
  {
    slug: "json-xml",
    name: "JSON to XML Converter",
    description: "Map nested JSON keys and array grids to structured, readable XML strings.",
    category: "Converters",
    popularity: 86,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "49K",
  },
  {
    slug: "xml-json",
    name: "XML to JSON Converter",
    description: "Convert XML data documents back into clean, parsed JSON hierarchies.",
    category: "Converters",
    popularity: 85,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "47K",
  },
  {
    slug: "hex-encoder",
    name: "String Hex Encoder & Decoder",
    description: "Translate string characters into space-separated hexadecimal bytes and back.",
    category: "Converters",
    popularity: 80,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "36K",
  },
  {
    slug: "line-sorter",
    name: "Text Line Sorter & Cleaner",
    description: "Clean lists: sort alphabetically or by size, deduplicate lines, and prune empty spaces.",
    category: "Developer Utilities",
    popularity: 87,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Braces",
    monthlyUses: "54K",
  },
  {
    slug: "yaml-toml",
    name: "YAML to TOML Converter",
    description: "Convert indentation-structured YAML parameters to config TOML keys and section headers.",
    category: "Converters",
    popularity: 89,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "65K",
  },
  {
    slug: "toml-yaml",
    name: "TOML to YAML Converter",
    description: "Translate config TOML values back into clean space-indented YAML configurations.",
    category: "Converters",
    popularity: 87,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "61K",
  },
  {
    slug: "base64-image",
    name: "Base64 Image Decoder & Previewer",
    description: "Convert encoded base64 image strings into full visual image previews with metadata metrics.",
    category: "Media Tools",
    popularity: 91,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "QrCode",
    monthlyUses: "76K",
  },
  {
    slug: "contrast-checker",
    name: "Color Contrast WCAG Checker",
    description: "Evaluate foreground and background color combinations against WCAG accessibility rules.",
    category: "Media Tools",
    popularity: 90,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "QrCode",
    monthlyUses: "73K",
  },
  {
    slug: "number-words",
    name: "Number to Words Translator",
    description: "Translate numeric integers into their formal English words representations.",
    category: "Converters",
    popularity: 83,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "41K",
  },
  {
    slug: "bcrypt-tester",
    name: "Bcrypt Password Verifier",
    description: "Verify password strings against standard bcrypt hashes in an interactive sandbox.",
    category: "Developer Utilities",
    popularity: 88,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "56K",
  },
  {
    slug: "screen-size",
    name: "Viewport & Screen Resolution Inspector",
    description: "Measure active client window widths, heights, pixel density ratio, and orientation metrics.",
    category: "Developer Utilities",
    popularity: 89,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "67K",
  },
  {
    slug: "lorem-code",
    name: "Lorem Code Snippet Generator",
    description: "Generate dummy code structures in JS, Python, HTML, or SQL for developer visual testing.",
    category: "Media Tools",
    popularity: 82,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "QrCode",
    monthlyUses: "38K",
  },
  {
    slug: "base64-size",
    name: "Base64 Size & Overhead Analyzer",
    description: "Compute original raw sizes and measure overhead increase percentages of base64 codes.",
    category: "Developer Utilities",
    popularity: 84,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "44K",
  },
  {
    slug: "lorem-lists",
    name: "Lorem HTML List Generator",
    description: "Assemble mockup ordered or unordered HTML list templates with random items.",
    category: "Media Tools",
    popularity: 81,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "QrCode",
    monthlyUses: "33K",
  },
  {
    slug: "subnet-calculator",
    name: "IP Subnet Calculator",
    description: "Calculate network addresses, subnet masks, broadcast addresses, and usable host ranges for any CIDR block.",
    category: "Developer Utilities",
    popularity: 85,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "55K",
  },
  {
    slug: "dns-lookup",
    name: "DNS Record Lookup",
    description: "Query and view standard DNS records (A, AAAA, MX, TXT) for any host or domain address.",
    category: "Developer Utilities",
    popularity: 86,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "48K",
  },
  {
    slug: "ping-test",
    name: "IP Ping Latency Test",
    description: "Simulate and measure network connectivity and ICMP response latency to any destination host.",
    category: "Developer Utilities",
    popularity: 82,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "39K",
  },
  {
    slug: "border-radius-generator",
    name: "CSS Border Radius Generator",
    description: "Visually design and preview custom CSS border-radius rules and export them as copyable styles.",
    category: "Media Tools",
    popularity: 88,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "QrCode",
    monthlyUses: "70K",
  },
  {
    slug: "glassmorphism-generator",
    name: "Glassmorphism CSS Generator",
    description: "Create premium glassmorphic UI design code using backdrop blur, opacity sliders, and borders.",
    category: "Media Tools",
    popularity: 93,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "QrCode",
    monthlyUses: "96K",
  },
  {
    slug: "prime-checker",
    name: "Prime Number Tester",
    description: "Verify if a number is prime and compute its prime factorization list instantly.",
    category: "Converters",
    popularity: 79,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "31K",
  },
  {
    slug: "fibonacci-generator",
    name: "Fibonacci Sequence Generator",
    description: "Generate and display Fibonacci sequences up to 50 terms instantly.",
    category: "Developer Utilities",
    popularity: 80,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Binary",
    monthlyUses: "34K",
  },
  {
    slug: "json-to-toml",
    name: "JSON to TOML Converter",
    description: "Convert JSON configuration objects to structured, clean TOML documents instantly.",
    category: "Converters",
    popularity: 87,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "52K",
  },
  {
    slug: "toml-to-json",
    name: "TOML to JSON Converter",
    description: "Translate TOML configuration values back into standard formatted JSON hierarchies.",
    category: "Converters",
    popularity: 86,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "RefreshCw",
    monthlyUses: "49K",
  },
  {
    slug: "caesar-cipher",
    name: "Caesar Cipher Encoder & Decoder",
    description: "Encode or decode messages using a shift-based Caesar cipher algorithm.",
    category: "Converters",
    popularity: 84,
    isAi: false,
    freeLimitPerDay: Infinity,
    icon: "Braces",
    monthlyUses: "41K",
  },
];
